### PR TITLE
update: remove lock file also add it in git ignore

### PR DESCRIPTION
**Pull request by AhsanSheraz**
Remove the poetry.lock file because it is recommended and it is built based on the operating system. For example, Linux-based poetry.lock will be useless for Windows users.

### CODE REVIEW

**Comment by AhsanSheraz** [comment]
@igormagalhaesr Thanks for this great boilerplate, please review this.

**Comment by igormagalhaesr** [comment]
Hey, @AhsanSheraz, thanks for the pull request!

Could you please expand more on the issue? The docs recommend commiting the poetry.lock file for applications, since the boilerplate is not a library I think it makes sense:

https://python-poetry.org/docs/basic-usage/#committing-your-poetrylock-file-to-version-control

**Comment by AhsanSheraz** [comment]
> Hey, @AhsanSheraz, thanks for the pull request!
> 
> Could you please expand more on the issue? The docs recommend commiting the poetry.lock file for applications, since the boilerplate is not a library I think it makes sense:
> 
> https://python-poetry.org/docs/basic-usage/#committing-your-poetrylock-file-to-version-control

@igormagalhaesr  So this case is valid for deployment but what happens if multiple developers are working on the same project on a different OS, in that case, it breaks things for other developers whenever someone adds a new library in the toml file. It's good to add when everyone has the same environment/OS. But this is boilerplate and can be used by multiple users with different OS, so it's better to remove it from the repo. For example, you are working on Linux and created this boilerplate, but when someone wants to use this in Windows he has to remove the lock file and create a new one based on his own OS.
Make sense?

**Comment by igormagalhaesr** [comment]
Yeah, it does. Thanks.

**Pull request merged**
